openapi: 3.0.0
info:
  title: workshop
  version: 1.0.0
paths:
  /files:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eirn93g54dsorr6ckf
        tag: $latest
        service_account: ajedpuh7juqg93mkj1o9
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4egj4kquqke5sbcodqr
        tag: $latest
        service_account: ajedpuh7juqg93mkj1o9
  /files/upload:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e1fnor0lm67o5f9q8c
        tag: $latest
        service_account: ajedpuh7juqg93mkj1o9
